function [response, RT] = collectChoiceResponse(window, Layout)

% collectChoiceResponse  Collect a mouse click on the choice grid.
%
%   [response, RT] = collectChoiceResponse(window, Layout)
%
%   Waits for the participant to click one of the 30 cells in the
%   choice-task grid.
%
%   Inputs:
%       window  - Psychtoolbox window pointer.
%       Layout  - Pixel-based layout generated by
%                 convertChoiceLayout.
%
%   Outputs:
%       response - Index of the clicked cell (1 ... 30).
%       RT       - Response time in seconds.
%
%   The function only collects the mouse response. It does not determine
%   which stimulus occupies the selected location or modify R.


startTime = GetSecs;

response = [];

while isempty(response)

    [x, y, buttons] = GetMouse(window);

    if any(buttons)

        for i = 1:size(Layout.rect, 1)

            if IsInRect(x, y, Layout.rect(i, :))

                response = i;
                break

            end

        end

    end

end

RT = GetSecs - startTime;

end