function Layout = convertChoiceLayout(Layout, screenRect)

% convertChoiceLayout  Convert normalized layout coordinates to pixels.
%
%   Layout = convertChoiceLayout(Layout, screenRect)
%
%   Converts the normalized coordinates produced by makeChoiceLayout
%   into Psychtoolbox pixel coordinates.
%
%   Normalized coordinates use the screen height as the reference
%   dimension for spatial sizes, so cells remain square regardless
%   of screen aspect ratio.
%
%   Inputs:
%       Layout      - Layout generated by makeChoiceLayout.
%       screenRect  - Psychtoolbox screen rectangle:
%                     [left top right bottom]
%
%   Output:
%       Layout      - Layout with pixel-based geometry.


screenWidth  = screenRect(3) - screenRect(1);
screenHeight = screenRect(4) - screenRect(2);

screenCenterX = screenWidth / 2;
screenCenterY = screenHeight / 2;


%% Stimulus rectangles

% Horizontal position uses screen width
xCenter = mean(Layout.rect(:, [1 3]), 2) * screenWidth;

% Horizontal size uses screen height
xHalfWidth = ...
    (Layout.rect(:, 3) - Layout.rect(:, 1)) * screenHeight / 2;

Layout.rect(:, 1) = ...
    screenCenterX + xCenter - xHalfWidth;

Layout.rect(:, 3) = ...
    screenCenterX + xCenter + xHalfWidth;


% Vertical position and size use screen height
yCenter = mean(Layout.rect(:, [2 4]), 2) * screenHeight;

yHalfHeight = ...
    (Layout.rect(:, 4) - Layout.rect(:, 2)) * screenHeight / 2;

Layout.rect(:, 2) = ...
    screenCenterY + yCenter - yHalfHeight;

Layout.rect(:, 4) = ...
    screenCenterY + yCenter + yHalfHeight;


%% Fixation tile

fixationWidth = ...
    (Layout.fixation(3) - Layout.fixation(1)) * screenHeight;

fixationHeight = ...
    (Layout.fixation(4) - Layout.fixation(2)) * screenHeight;

fixationCenterX = ...
    mean(Layout.fixation([1 3])) * screenHeight;

fixationCenterY = ...
    mean(Layout.fixation([2 4])) * screenHeight;

Layout.fixation = [ ...
    screenCenterX + fixationCenterX - fixationWidth / 2, ...
    screenCenterY + fixationCenterY - fixationHeight / 2, ...
    screenCenterX + fixationCenterX + fixationWidth / 2, ...
    screenCenterY + fixationCenterY + fixationHeight / 2];


%% Fixation cross

Layout.fixationCross.horizontal([1 3]) = ...
    Layout.fixationCross.horizontal([1 3]) * screenHeight ...
    + screenCenterX;

Layout.fixationCross.horizontal([2 4]) = ...
    Layout.fixationCross.horizontal([2 4]) * screenHeight ...
    + screenCenterY;

Layout.fixationCross.vertical([1 3]) = ...
    Layout.fixationCross.vertical([1 3]) * screenHeight ...
    + screenCenterX;

Layout.fixationCross.vertical([2 4]) = ...
    Layout.fixationCross.vertical([2 4]) * screenHeight ...
    + screenCenterY;


end