function Layout = convertQuestionnaireLayout(Layout, screenRect)

% convertQuestionnaireLayout  Convert normalized questionnaire layout
%                             coordinates to pixels.
%
%   Layout = convertQuestionnaireLayout(Layout, screenRect)
%
%   Converts the normalized coordinates produced by
%   makeQuestionnaireLayout into Psychtoolbox pixel coordinates.
%
%   Normalized coordinates:
%       x = -0.5 ... +0.5
%       y = -0.5 ... +0.5
%
%   Inputs:
%       Layout      - Layout generated by makeQuestionnaireLayout.
%       screenRect  - Psychtoolbox screen rectangle:
%                     [left top right bottom]
%
%   Output:
%       Layout      - Layout with pixel-based rectangles.
%
%   The function only converts coordinates. It does not draw anything
%   or modify the questionnaire geometry.


%% Screen properties

screenWidth  = screenRect(3) - screenRect(1);
screenHeight = screenRect(4) - screenRect(2);

screenCenterX = screenWidth / 2;
screenCenterY = screenHeight / 2;


%% Instruction image

Layout.instruction(:, [1 3]) = ...
    Layout.instruction(:, [1 3]) * screenWidth + screenCenterX;

Layout.instruction(:, [2 4]) = ...
    Layout.instruction(:, [2 4]) * screenHeight + screenCenterY;


%% Question images

Layout.question(:, [1 3]) = ...
    Layout.question(:, [1 3]) * screenWidth + screenCenterX;

Layout.question(:, [2 4]) = ...
    Layout.question(:, [2 4]) * screenHeight + screenCenterY;


%% Response buttons

Layout.button(:, :, [1 3]) = ...
    Layout.button(:, :, [1 3]) * screenWidth + screenCenterX;

Layout.button(:, :, [2 4]) = ...
    Layout.button(:, :, [2 4]) * screenHeight + screenCenterY;

end