function Layout = convertChoiceLayout(Layout, screenRect)

% convertChoiceLayout  Convert normalized layout coordinates to pixels.
%
%   Layout = convertChoiceLayout(Layout, screenRect)
%
%   Converts the normalized coordinates produced by makeChoiceLayout
%   into Psychtoolbox pixel coordinates.
%
%   Normalized coordinates:
%       x = -0.5 ... +0.5
%       y = -0.5 ... +0.5
%
%   Inputs:
%       Layout      - Layout generated by makeChoiceLayout.
%       screenRect  - Psychtoolbox screen rectangle:
%                     [left top right bottom]
%
%   Output:
%       Layout      - Layout with pixel-based rectangles.
%
%   The normalized layout is overwritten with pixel coordinates.


screenWidth = screenRect(3) - screenRect(1);
screenHeight = screenRect(4) - screenRect(2);

screenCenterX = screenWidth / 2;
screenCenterY = screenHeight / 2;


%% Stimulus rectangles

Layout.rect(:, [1 3]) = ...
    Layout.rect(:, [1 3]) * screenWidth + screenCenterX;

Layout.rect(:, [2 4]) = ...
    Layout.rect(:, [2 4]) * screenHeight + screenCenterY;


%% Fixation rectangle

Layout.fixation([1 3]) = ...
    Layout.fixation([1 3]) * screenWidth + screenCenterX;

Layout.fixation([2 4]) = ...
    Layout.fixation([2 4]) * screenHeight + screenCenterY;


end