function drawChoiceSet(P, T, ChoiceSet, Layout, positions)

% drawChoiceSet  Draw one choice-set display.
%
%   drawChoiceSet(P, T, ChoiceSet, Layout, positions)
%
%   Loads and draws the stimuli in ChoiceSet at their assigned locations
%   and fills all remaining locations with the choice-set mask.
%
%   Inputs:
%       P         - Parameter structure.
%       T         - Task structure.
%       ChoiceSet - Image IDs belonging to the current trial.
%       Layout    - Pixel-based layout generated by
%                   convertChoiceLayout.
%       positions - Location assignment generated by
%                   randomizeChoicePositions.
%
%   The function only draws. It does not randomize, convert coordinates,
%   collect responses, or modify results.


%% Draw stimuli

for i = 1:numel(ChoiceSet)

    imageID = ChoiceSet(i);
    location = positions.stimulus(i);

    % Load image
    [textureID, imageWidth, imageHeight] = ...
        readimg(P.Images.files{imageID}, T.window);

    % Fit image inside its spatial cell
    cellRect = Layout.rect(location, :);

    cellWidth  = cellRect(3) - cellRect(1);
    cellHeight = cellRect(4) - cellRect(2);

    scale = min( ...
        cellWidth / imageWidth, ...
        cellHeight / imageHeight);

    drawWidth  = imageWidth  * scale;
    drawHeight = imageHeight * scale;

    imageRect = CenterRectOnPoint( ...
        [0 0 drawWidth drawHeight], ...
        (cellRect(1) + cellRect(3)) / 2, ...
        (cellRect(2) + cellRect(4)) / 2);

    Screen('DrawTexture', ...
        T.window, ...
        textureID, ...
        [], ...
        imageRect);

    % Texture is no longer needed after drawing
    Screen('Close', textureID);

end


%% Draw masks

for i = 1:numel(positions.empty)

    location = positions.empty(i);

    Screen('FillRect', ...
        T.window, ...
        P.Choice.Layout.maskColor, ...
        Layout.rect(location, :));

end

end