function drawQuestionnaire( ...
    P, T, Layout, questionFiles, questionIndex)

% drawQuestionnaire
%
% Draw one questionnaire trial.
%
% Each screen contains:
%
%       Q0 instruction image
%
%       current question image
%
%       rating buttons: 1 ... nScalePoints
%
% This function performs DRAWING ONLY.
%
% It does not:
%       - collect responses
%       - measure RT
%       - draw hover highlighting
%       - draw selection feedback
%       - flip the screen
%
% Those responsibilities belong to the questionnaire response
% collection layer.
%
% Inputs:
%
%       P
%           Experiment parameters.
%
%       T
%           Runtime task structure.
%
%       Layout
%           Pixel-based questionnaire layout generated by:
%
%               makeQuestionnaireLayout
%               convertQuestionnaireLayout
%
%       questionFiles
%           Cell array:
%
%               {Q0, Q1, Q2, ... Qn}
%
%       questionIndex
%           Current questionnaire question:
%
%               1 ... P.Questionnaire.nQuestions


%% ==============================================================
% Validate Question Index
% ==============================================================

if questionIndex < 1 || ...
        questionIndex > P.Questionnaire.nQuestions

    error( ...
        'Invalid questionnaire question index: %d', ...
        questionIndex);

end


requiredFiles = ...
    P.Questionnaire.nQuestions + 1;


if numel(questionFiles) < requiredFiles

    error( ...
        ['Expected at least %d questionnaire files, ' ...
         'but received %d.'], ...
        requiredFiles, ...
        numel(questionFiles));

end


%% ==============================================================
% Background
% ==============================================================

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Screen.backgroundColor);


%% ==============================================================
% Q0 — General Instruction
% ==============================================================

[textureID, imageWidth, imageHeight] = ...
    readimg( ...
        questionFiles{1}, ...
        T.window);


instructionWidth = ...
    Layout.instruction(3) - ...
    Layout.instruction(1);


instructionHeight = ...
    Layout.instruction(4) - ...
    Layout.instruction(2);


scale = min( ...
    instructionWidth / imageWidth, ...
    instructionHeight / imageHeight);


drawWidth = ...
    imageWidth * scale;


drawHeight = ...
    imageHeight * scale;


instructionRect = CenterRectOnPoint( ...
    [0 0 drawWidth drawHeight], ...
    mean(Layout.instruction([1 3])), ...
    mean(Layout.instruction([2 4])));


Screen( ...
    'DrawTexture', ...
    T.window, ...
    textureID, ...
    [], ...
    instructionRect);


Screen( ...
    'Close', ...
    textureID);


%% ==============================================================
% Current Question
% ==============================================================

questionFile = ...
    questionFiles{questionIndex + 1};


[textureID, imageWidth, imageHeight] = ...
    readimg( ...
        questionFile, ...
        T.window);


questionWidth = ...
    Layout.question(3) - ...
    Layout.question(1);


questionHeight = ...
    Layout.question(4) - ...
    Layout.question(2);


scale = min( ...
    questionWidth / imageWidth, ...
    questionHeight / imageHeight);


drawWidth = ...
    imageWidth * scale;


drawHeight = ...
    imageHeight * scale;


questionRect = CenterRectOnPoint( ...
    [0 0 drawWidth drawHeight], ...
    mean(Layout.question([1 3])), ...
    mean(Layout.question([2 4])));


Screen( ...
    'DrawTexture', ...
    T.window, ...
    textureID, ...
    [], ...
    questionRect);


Screen( ...
    'Close', ...
    textureID);


%% ==============================================================
% Rating Scale
% ==============================================================

for scalePoint = 1:P.Questionnaire.nScalePoints


    rect = ...
        Layout.button(scalePoint, :);


    %% ----------------------------------------------------------
    % Button Border
    % -----------------------------------------------------------

    Screen( ...
        'FrameRect', ...
        T.window, ...
        P.Screen.textColor, ...
        rect, ...
        P.Questionnaire.Layout.buttonBorderWidth);


    %% ----------------------------------------------------------
    % Button Number
    % -----------------------------------------------------------

    DrawFormattedText( ...
        T.window, ...
        num2str(scalePoint), ...
        'center', ...
        'center', ...
        P.Screen.textColor, ...
        [], ...     % wrapat
        [], ...     % flipHorizontal
        [], ...     % flipVertical
        [], ...     % vSpacing
        [], ...     % righttoleft
        rect);      % winRect


end


end