function drawQuestionnaire(P, T, Layout, questionFiles, response)

% drawQuestionnaire  Draw the questionnaire screen.
%
%   drawQuestionnaire(P, T, Layout, questionFiles, response)
%
%   Draws the general instruction, questions, and Likert buttons.
%   Selected responses are highlighted with a green border.
%
%   response is a 1 x nQuestions vector. NaN indicates that the
%   corresponding question has not yet been answered.


%% ==============================================================
% Instruction
% ==============================================================

[textureID, imageWidth, imageHeight] = ...
    readimg(questionFiles{1}, T.window);

scale = min( ...
    (Layout.instruction(3) - Layout.instruction(1)) / imageWidth, ...
    (Layout.instruction(4) - Layout.instruction(2)) / imageHeight);

drawWidth  = imageWidth  * scale;
drawHeight = imageHeight * scale;

instructionRect = CenterRectOnPoint( ...
    [0 0 drawWidth drawHeight], ...
    mean(Layout.instruction([1 3])), ...
    mean(Layout.instruction([2 4])));

Screen('DrawTexture', ...
    T.window, ...
    textureID, ...
    [], ...
    instructionRect);

Screen('Close', textureID);


%% ==============================================================
% Questions
% ==============================================================

for question = 1:P.Questionnaire.nQuestions

    %% Question image

    [textureID, imageWidth, imageHeight] = ...
        readimg(questionFiles{question + 1}, T.window);

    scale = min( ...
        (Layout.question(question, 3) - Layout.question(question, 1)) ...
            / imageWidth, ...
        (Layout.question(question, 4) - Layout.question(question, 2)) ...
            / imageHeight);

    drawWidth  = imageWidth  * scale;
    drawHeight = imageHeight * scale;

    questionRect = CenterRectOnPoint( ...
        [0 0 drawWidth drawHeight], ...
        mean(Layout.question(question, [1 3])), ...
        mean(Layout.question(question, [2 4])));

    Screen('DrawTexture', ...
        T.window, ...
        textureID, ...
        [], ...
        questionRect);

    Screen('Close', textureID);


    %% Response buttons

    for scalePoint = 1:P.Questionnaire.nScalePoints

        rect = Layout.button(question, scalePoint, :);
        rect = rect(:)';


        % Normal button border

        Screen('FrameRect', ...
            T.window, ...
            P.Screen.textColor, ...
            rect, ...
            P.Questionnaire.Layout.buttonBorderWidth);


        % Button number

        DrawFormattedText( ...
            T.window, ...
            num2str(scalePoint), ...
            'center', ...
            'center', ...
            P.Screen.textColor, ...
            [], ...
            [], ...
            [], ...
            [], ...
            rect);


        % Highlight selected response

        if ~isnan(response(question)) && ...
                response(question) == scalePoint

            Screen('FrameRect', ...
                T.window, ...
                P.Questionnaire.Layout.selectedColor, ...
                rect, ...
                P.Questionnaire.Layout.selectedBorderWidth);

        end

    end

end

end