function drawRatingScreen(textureID, imageRect, rating, P, T)

% Clear screen
Screen('FillRect', T.window, P.Screen.backgroundColor);

%% Draw image
Screen('DrawTexture', T.window, textureID, [], imageRect);

%% Draw rating scale

lineY = round(T.height * 0.80);

x0 = round(T.width * 0.20);
x1 = round(T.width * 0.80);

Screen('DrawLine', T.window, ...
    P.Screen.textColor, ...
    x0, lineY, ...
    x1, lineY, ...
    3);

% Tick marks and labels
for value = 0:10

    x = x0 + (value/10) * (x1-x0);

    Screen('DrawLine', T.window, ...
        P.Screen.textColor, ...
        x, lineY-10, ...
        x, lineY+10, ...
        2);

    DrawFormattedText( ...
        T.window, ...
        num2str(value), ...
        x-6, ...
        lineY+20, ...
        P.Screen.textColor);
end

%% Draw slider

sliderX = x0 + (rating/10) * (x1-x0);

Screen('FillOval', ...
    T.window, ...
    [255 0 0], ...
    [sliderX-8 lineY-8 sliderX+8 lineY+8]);

%% Instructions

DrawFormattedText( ...
    T.window, ...
    [char(8592) ' Move      SPACE  Confirm'], ...
    'center', ...
    round(T.height*0.92), ...
    P.Screen.textColor);

%% Progress

progressWidth = round(T.width*0.30);

progressHeight = 18;

progressX = round((T.width-progressWidth)/2);

progressY = round(T.height*0.96);

Screen('FrameRect',...
    T.window,...
    P.Screen.textColor,...
    [progressX progressY ...
     progressX+progressWidth ...
     progressY+progressHeight],2);

Screen('FillRect',...
    T.window,...
    [100 220 100],...
    [progressX progressY ...
     progressX + progressWidth*T.progress ...
     progressY+progressHeight]);

DrawFormattedText(...
    T.window,...
    sprintf('%d%% Complete',round(T.progress*100)),...
    'center',...
    progressY-25,...
    P.Screen.textColor);

%% Flip

Screen('Flip',T.window);

end