function drawChoiceSet(window, textures, ChoiceSet, Layout, positions, maskTexture)

% drawChoiceSet  Draw one choice-set display.
%
%   drawChoiceSet(window, textures, ChoiceSet, Layout, ...
%                 positions, maskTexture)
%
%   Draws the stimuli in ChoiceSet at their assigned locations and
%   fills all remaining locations with the mask texture.
%
%   Inputs:
%       window      - Psychtoolbox window pointer.
%       textures    - PTB textures indexed by image ID.
%       ChoiceSet   - Image IDs belonging to the current trial.
%       Layout      - Pixel-based layout generated by
%                     convertChoiceLayout.
%       positions   - Location assignment generated by
%                     randomizeChoicePositions.
%       maskTexture - PTB texture used for empty locations.
%
%   The function only draws. It does not randomize, convert coordinates,
%   collect responses, or modify results.


%% Draw stimuli

for i = 1:numel(ChoiceSet)

    imageID = ChoiceSet(i);
    location = positions.stimulus(i);

    Screen('DrawTexture', ...
        window, ...
        textures(imageID), ...
        [], ...
        Layout.rect(location, :));

end


%% Draw masks

for i = 1:numel(positions.empty)

    location = positions.empty(i);

    Screen('DrawTexture', ...
        window, ...
        maskTexture, ...
        [], ...
        Layout.rect(location, :));

end

end