function positions = randomizeChoicePositions(Layout, setSize)

% randomizeChoicePositions  Randomly assign occupied locations.
%
%   positions = randomizeChoicePositions(Layout, setSize)
%
%   Randomly selects setSize locations from the 30 fixed locations
%   generated by makeChoiceLayout. The remaining locations are
%   available for masking.
%
%   Inputs:
%       Layout  - Spatial layout generated by makeChoiceLayout.
%       setSize - Number of stimuli presented on the current trial.
%
%   Output:
%       positions.stimulus - Indices of occupied locations.
%       positions.empty     - Indices of unoccupied locations.
%
%   The function only handles spatial randomization. It does not assign
%   stimuli or conditions to the selected locations.

nLocations = size(Layout.rect, 1);

order = randperm(nLocations);

positions.stimulus = order(1:setSize);
positions.empty = order(setSize + 1:end);

end