function trial = runChoiceTrial( ...
    P, T, ChoiceSet, condition, ...
    ChoiceLayout, QuestionnaireLayout, questionFiles)

% runChoiceTrial
%
% Run one complete choice-task trial.
%
% Trial sequence:
%
%       Fixation
%       Exposure
%       Mask
%       Response
%       Questionnaire
%
%
% Timing-critical Choice events:
%
%       CHOICE_FIXATION
%       CHOICE_EXPOSURE
%       CHOICE_MASK
%       CHOICE_RESPONSE_ONSET
%
%
% Response and miss events are handled inside
% collectChoiceResponse so they can be emitted immediately when
% the response or timeout is detected.


%% ==============================================================
% Initialize Trial Result
% ==============================================================

trial = struct( ...
    'choiceSet',     ChoiceSet, ...
    'condition',     condition, ...
    'positions',     [], ...
    'response',      [], ...
    'selectedImage', NaN, ...
    'RT',            NaN, ...
    'question',      struct( ...
        'response', nan(1, P.Questionnaire.nQuestions), ...
        'RT',       nan(1, P.Questionnaire.nQuestions)));


stimulusIDs = ...
    ChoiceSet;


condition = ...
    string(condition);


setSize = ...
    numel(stimulusIDs);


%% ==============================================================
% Resolve Exposure Event Code
% ==============================================================

% Choice exposure is the main experimental manipulation.
%
% Each Set Size x Condition combination has its own EEG code.

exposureCode = getChoiceExposureCode( ...
    P, ...
    setSize, ...
    condition);


%% ==============================================================
% Prepare Response Events
% ==============================================================

% These are passed into collectChoiceResponse because response
% and timeout events must be emitted at the moment they are
% detected, before any feedback delay.


ResponseEvent.responseName = sprintf( ...
    'CHOICE_RESPONSE setSize=%d condition=%s', ...
    setSize, ...
    char(condition));


ResponseEvent.responseCode = ...
    P.Events.Choice.response;


ResponseEvent.missName = sprintf( ...
    'CHOICE_MISS setSize=%d condition=%s', ...
    setSize, ...
    char(condition));


ResponseEvent.missCode = ...
    P.Events.Choice.miss;


%% ==============================================================
% Assign Stimuli to Spatial Locations
% ==============================================================

positions = randomizeChoicePositions( ...
    ChoiceLayout, ...
    numel(stimulusIDs));


trial.positions = ...
    positions;


%% ==============================================================
% Fixation
% ==============================================================

HideCursor;


Screen( ...
    'FillRect', ...
    T.window, ...
    P.Screen.backgroundColor);


%% Fixation Tile

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Choice.Layout.maskColor, ...
    ChoiceLayout.fixation);


%% Horizontal Fixation Line

Screen( ...
    'DrawLine', ...
    T.window, ...
    P.Choice.Layout.fixationColor, ...
    ChoiceLayout.fixationCross.horizontal(1), ...
    ChoiceLayout.fixationCross.horizontal(2), ...
    ChoiceLayout.fixationCross.horizontal(3), ...
    ChoiceLayout.fixationCross.horizontal(4), ...
    P.Choice.Layout.fixationCrossWidth);


%% Vertical Fixation Line

Screen( ...
    'DrawLine', ...
    T.window, ...
    P.Choice.Layout.fixationColor, ...
    ChoiceLayout.fixationCross.vertical(1), ...
    ChoiceLayout.fixationCross.vertical(2), ...
    ChoiceLayout.fixationCross.vertical(3), ...
    ChoiceLayout.fixationCross.vertical(4), ...
    P.Choice.Layout.fixationCrossWidth);


%% --------------------------------------------------------------
% Fixation Onset
% ---------------------------------------------------------------

fixationOnset = ...
    Screen('Flip', T.window);


%% --------------------------------------------------------------
% Fixation Event
% ---------------------------------------------------------------

eventName = sprintf( ...
    'CHOICE_FIXATION setSize=%d condition=%s', ...
    setSize, ...
    char(condition));


sendEvent( ...
    P, ...
    T, ...
    "Choice", ...
    eventName, ...
    P.Events.Choice.fixation);


%% --------------------------------------------------------------
% Maintain Fixation
% ---------------------------------------------------------------

WaitSecs( ...
    'UntilTime', ...
    fixationOnset + P.Choice.fixationDuration);


%% ==============================================================
% Exposure
% ==============================================================

% No response highlighting is shown during exposure.

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Screen.backgroundColor);


drawChoiceSet( ...
    P, ...
    T, ...
    stimulusIDs, ...
    ChoiceLayout, ...
    positions);


%% --------------------------------------------------------------
% Exposure Onset
% ---------------------------------------------------------------

exposureOnset = ...
    Screen('Flip', T.window);


%% --------------------------------------------------------------
% Exposure Event
% ---------------------------------------------------------------

eventName = sprintf( ...
    'CHOICE_EXPOSURE setSize=%d condition=%s', ...
    setSize, ...
    char(condition));


sendEvent( ...
    P, ...
    T, ...
    "Choice", ...
    eventName, ...
    exposureCode);


%% --------------------------------------------------------------
% Maintain Exposure
% ---------------------------------------------------------------

WaitSecs( ...
    'UntilTime', ...
    exposureOnset + P.Choice.exposureDuration);


%% ==============================================================
% Mask
% ==============================================================

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Screen.backgroundColor);


Screen( ...
    'FillRect', ...
    T.window, ...
    P.Choice.Layout.maskColor, ...
    ChoiceLayout.rect');


%% --------------------------------------------------------------
% Mask Onset
% ---------------------------------------------------------------

maskOnset = ...
    Screen('Flip', T.window);


%% --------------------------------------------------------------
% Mask Event
% ---------------------------------------------------------------

eventName = sprintf( ...
    'CHOICE_MASK setSize=%d condition=%s', ...
    setSize, ...
    char(condition));


sendEvent( ...
    P, ...
    T, ...
    "Choice", ...
    eventName, ...
    P.Events.Choice.mask);


%% --------------------------------------------------------------
% Maintain Mask
% ---------------------------------------------------------------

WaitSecs( ...
    'UntilTime', ...
    maskOnset + P.Choice.maskDuration);


% %% ==============================================================
% % Choice Fixation
% % ==============================================================
%
% Screen( ...
%     'FillRect', ...
%     T.window, ...
%     P.Screen.backgroundColor);
%
%
% %% Fixation Border
%
% Screen( ...
%     'FrameRect', ...
%     T.window, ...
%     P.Choice.Layout.fixationColor, ...
%     ChoiceLayout.fixation, ...
%     P.Choice.Layout.fixationBorderWidth);
%
%
% %% Horizontal Fixation Line
%
% Screen( ...
%     'DrawLine', ...
%     T.window, ...
%     P.Choice.Layout.fixationColor, ...
%     ChoiceLayout.fixationCross.horizontal(1), ...
%     ChoiceLayout.fixationCross.horizontal(2), ...
%     ChoiceLayout.fixationCross.horizontal(3), ...
%     ChoiceLayout.fixationCross.horizontal(4), ...
%     P.Choice.Layout.fixationCrossWidth);
%
%
% %% Vertical Fixation Line
%
% Screen( ...
%     'DrawLine', ...
%     T.window, ...
%     P.Choice.Layout.fixationColor, ...
%     ChoiceLayout.fixationCross.vertical(1), ...
%     ChoiceLayout.fixationCross.vertical(2), ...
%     ChoiceLayout.fixationCross.vertical(3), ...
%     ChoiceLayout.fixationCross.vertical(4), ...
%     P.Choice.Layout.fixationCrossWidth);
%
%
% Screen('Flip', T.window);
%
% WaitSecs(P.Choice.choiceFixationDuration);


%% ==============================================================
% Create Response Cache
% ==============================================================

% Create an offscreen window with the same size and graphics context
% as the participant display.
%
% IMPORTANT:
%
% We do NOT call drawChoiceSet using this window.
%
% readimg -> Screen('MakeTexture') must continue using T.window.

responseBuffer = Screen( ...
    'OpenOffscreenWindow', ...
    T.window, ...
    P.Screen.backgroundColor);


%% ==============================================================
% Build Clean Response Screen
% ==============================================================

% Draw the clean response display normally into the REAL onscreen
% window backbuffer.

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Screen.backgroundColor);


drawChoiceSet( ...
    P, ...
    T, ...
    stimulusIDs, ...
    ChoiceLayout, ...
    positions);


%% ==============================================================
% Cache Clean Response Screen
% ==============================================================

% Copy the completed clean response display from the onscreen
% backbuffer into the offscreen cache.
%
% From this point onward, hover updates can restore the screen from
% responseBuffer without loading images again.

Screen( ...
    'CopyWindow', ...
    T.window, ...
    responseBuffer);


%% ==============================================================
% Reset Mouse Position
% ==============================================================

% Recenter the mouse at the fixation cell at the beginning
% of every choice trial.

mouseStartX = round( ...
    mean(ChoiceLayout.fixation([1 3])));


mouseStartY = round( ...
    mean(ChoiceLayout.fixation([2 4])));


SetMouse( ...
    mouseStartX, ...
    mouseStartY, ...
    T.window);


%% ==============================================================
% Response Phase Onset
% ==============================================================

% The clean response display is already present in the onscreen
% backbuffer from drawChoiceSet.
%
% Add the yellow fixation cue before the first response-phase flip.

ShowCursor('Arrow');


drawResponseHighlight( ...
    T.window, ...
    ChoiceLayout.fixation, ...
    P.Choice.Highlight.hoverColor, ...
    P.Choice.Highlight.borderWidth);


%% --------------------------------------------------------------
% Response Onset Flip
% ---------------------------------------------------------------

% This flip marks the true response-phase onset.

choiceOnset = ...
    Screen('Flip', T.window);


%% --------------------------------------------------------------
% Response Onset Event
% ---------------------------------------------------------------

eventName = sprintf( ...
    'CHOICE_RESPONSE_ONSET setSize=%d condition=%s', ...
    setSize, ...
    char(condition));


sendEvent( ...
    P, ...
    T, ...
    "Choice", ...
    eventName, ...
    P.Events.Choice.responseOnset);


%% ==============================================================
% Collect Choice Response
% ==============================================================

[response, RT] = collectChoiceResponse( ...
    P, ...
    T, ...
    responseBuffer, ...
    ChoiceLayout, ...
    positions.stimulus, ...
    choiceOnset, ...
    P.Choice.choiceDuration, ...
    P.Choice.Highlight, ...
    ResponseEvent);


trial.response = ...
    response;


trial.RT = ...
    RT;


%% ==============================================================
% Close Response Cache
% ==============================================================

Screen( ...
    'Close', ...
    responseBuffer);


%% ==============================================================
% Missed Trial
% ==============================================================

if isempty(response)

    trial.selectedImage = ...
        NaN;


    % Questionnaire fields already contain NaN values.
    %
    % CHOICE_MISS has already been emitted inside
    % collectChoiceResponse at the actual timeout.
    %
    % Skip questionnaire after a missed choice.

    return;

end


%% ==============================================================
% Determine Selected Image
% ==============================================================

stimulusIndex = find( ...
    positions.stimulus == response, ...
    1, ...
    'first');


if isempty(stimulusIndex)

    error( ...
        'Choice response location %d does not contain a stimulus.', ...
        response);

end


trial.selectedImage = ...
    stimulusIDs(stimulusIndex);


%% ==============================================================
% Questionnaire
% ==============================================================

[questionResponse, questionRT] = runQuestionnaire( ...
    P, ...
    T, ...
    QuestionnaireLayout, ...
    questionFiles);


trial.question.response = ...
    questionResponse;


trial.question.RT = ...
    questionRT;


end