function trial = runChoiceTrial( ...
    window, textures, ChoiceSet, Layout, maskTexture)

% runChoiceTrial  Run one choice-task trial.
%
%   trial = runChoiceTrial( ...
%       window, textures, ChoiceSet, Layout, maskTexture)
%
%   Presents one choice set, randomly assigns its stimuli to spatial
%   locations, displays the choice screen, and collects the participant's
%   mouse response.
%
%   Inputs:
%       window      - Psychtoolbox window pointer.
%       textures    - PTB textures indexed by image ID.
%       ChoiceSet   - Image IDs belonging to the current trial.
%       Layout      - Pixel-based layout generated by
%                     convertChoiceLayout.
%       maskTexture - PTB texture used for empty locations.
%
%   Output:
%       trial       - Structure containing:
%                       .choiceSet
%                       .positions
%                       .response
%                       .selectedImage
%                       .RT
%
%   The function only handles the sequence of one trial. It does not
%   generate choice sets, define the layout, or modify R.


%% Assign stimuli to spatial locations

setSize = numel(ChoiceSet);

positions = randomizeChoicePositions(Layout, setSize);


%% Draw choice set

drawChoiceSet( ...
    window, ...
    textures, ...
    ChoiceSet, ...
    Layout, ...
    positions, ...
    maskTexture);


%% Present choice set

Screen('Flip', window);


%% Collect response

[response, RT] = collectChoiceResponse(window, Layout);


%% Determine selected image

selectedImage = ChoiceSet( ...
    find(positions.stimulus == response));


%% Store trial information

trial.choiceSet = ChoiceSet;
trial.positions = positions;
trial.response = response;
trial.selectedImage = selectedImage;
trial.RT = RT;

end