function trial = runChoiceTrial( ...
    P, T, ChoiceSet, condition, ...
    ChoiceLayout, QuestionnaireLayout, questionFiles)

% runChoiceTrial  Run one complete choice-task trial.
%
%   trial = runChoiceTrial( ...
%       P, T, ChoiceSet, condition, ...
%       ChoiceLayout, QuestionnaireLayout, questionFiles)
%
%   Trial sequence:
%
%       Fixation
%       Exposure
%       Mask
%       Choice fixation
%       Response
%       Questionnaire
%
%   Response highlighting:
%
%       Response onset:
%           Yellow border around fixation
%
%       Hover valid stimulus:
%           Yellow border around stimulus
%
%       Mouse outside valid stimuli:
%           No highlight
%
%       Valid click:
%           Green border around selected stimulus
%
%   The yellow fixation border appears only at response onset.
%   It does not return after mouse movement begins.


%% ==============================================================
% Initialize Trial Result
% ==============================================================

trial = struct( ...
    'choiceSet',     ChoiceSet, ...
    'condition',     condition, ...
    'positions',     [], ...
    'response',      [], ...
    'selectedImage', NaN, ...
    'RT',            NaN, ...
    'question',      struct( ...
        'response', nan(1, P.Questionnaire.nQuestions), ...
        'RT',       nan(1, P.Questionnaire.nQuestions)));


stimulusIDs = ChoiceSet;


%% ==============================================================
% Assign Stimuli to Spatial Locations
% ==============================================================

positions = randomizeChoicePositions( ...
    ChoiceLayout, ...
    numel(stimulusIDs));


trial.positions = positions;


%% ==============================================================
% Fixation
% ==============================================================

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Screen.backgroundColor);


%% Fixation tile

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Choice.Layout.maskColor, ...
    ChoiceLayout.fixation);


%% Horizontal fixation line

Screen( ...
    'DrawLine', ...
    T.window, ...
    P.Choice.Layout.fixationColor, ...
    ChoiceLayout.fixationCross.horizontal(1), ...
    ChoiceLayout.fixationCross.horizontal(2), ...
    ChoiceLayout.fixationCross.horizontal(3), ...
    ChoiceLayout.fixationCross.horizontal(4), ...
    P.Choice.Layout.fixationCrossWidth);


%% Vertical fixation line

Screen( ...
    'DrawLine', ...
    T.window, ...
    P.Choice.Layout.fixationColor, ...
    ChoiceLayout.fixationCross.vertical(1), ...
    ChoiceLayout.fixationCross.vertical(2), ...
    ChoiceLayout.fixationCross.vertical(3), ...
    ChoiceLayout.fixationCross.vertical(4), ...
    P.Choice.Layout.fixationCrossWidth);


Screen('Flip', T.window);

WaitSecs(P.Choice.fixationDuration);


%% ==============================================================
% Exposure
% ==============================================================

% No response highlighting is shown during exposure.

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Screen.backgroundColor);


drawChoiceSet( ...
    P, ...
    T, ...
    stimulusIDs, ...
    ChoiceLayout, ...
    positions);


Screen('Flip', T.window);

WaitSecs(P.Choice.exposureDuration);


%% ==============================================================
% Mask
% ==============================================================

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Screen.backgroundColor);


Screen( ...
    'FillRect', ...
    T.window, ...
    P.Choice.Layout.maskColor, ...
    ChoiceLayout.rect');


Screen('Flip', T.window);

WaitSecs(P.Choice.maskDuration);


% %% ==============================================================
% % Choice Fixation
% % ==============================================================
% 
% Screen( ...
%     'FillRect', ...
%     T.window, ...
%     P.Screen.backgroundColor);
% 
% 
% %% Fixation border
% 
% Screen( ...
%     'FrameRect', ...
%     T.window, ...
%     P.Choice.Layout.fixationColor, ...
%     ChoiceLayout.fixation, ...
%     P.Choice.Layout.fixationBorderWidth);
% 
% 
% %% Horizontal fixation line
% 
% Screen( ...
%     'DrawLine', ...
%     T.window, ...
%     P.Choice.Layout.fixationColor, ...
%     ChoiceLayout.fixationCross.horizontal(1), ...
%     ChoiceLayout.fixationCross.horizontal(2), ...
%     ChoiceLayout.fixationCross.horizontal(3), ...
%     ChoiceLayout.fixationCross.horizontal(4), ...
%     P.Choice.Layout.fixationCrossWidth);
% 
% 
% %% Vertical fixation line
% 
% Screen( ...
%     'DrawLine', ...
%     T.window, ...
%     P.Choice.Layout.fixationColor, ...
%     ChoiceLayout.fixationCross.vertical(1), ...
%     ChoiceLayout.fixationCross.vertical(2), ...
%     ChoiceLayout.fixationCross.vertical(3), ...
%     ChoiceLayout.fixationCross.vertical(4), ...
%     P.Choice.Layout.fixationCrossWidth);
% 
% 
% Screen('Flip', T.window);
% 
% WaitSecs(P.Choice.choiceFixationDuration);


%% ==============================================================
% Create Response Cache
% ==============================================================

% Create an offscreen window with the same size and graphics context
% as the participant display.
%
% IMPORTANT:
% We do NOT call drawChoiceSet using this window.
%
% readimg -> Screen('MakeTexture') must continue using T.window.

responseBuffer = Screen( ...
    'OpenOffscreenWindow', ...
    T.window, ...
    P.Screen.backgroundColor);


%% ==============================================================
% Build Clean Response Screen
% ==============================================================

% Draw the clean response display normally into the REAL onscreen
% window backbuffer.

Screen( ...
    'FillRect', ...
    T.window, ...
    P.Screen.backgroundColor);


drawChoiceSet( ...
    P, ...
    T, ...
    stimulusIDs, ...
    ChoiceLayout, ...
    positions);


%% ==============================================================
% Cache Clean Response Screen
% ==============================================================

% Copy the completed clean response display from the onscreen
% backbuffer into the offscreen cache.
%
% From this point onward, hover updates can restore the screen from
% responseBuffer without loading images again.

Screen( ...
    'CopyWindow', ...
    T.window, ...
    responseBuffer);


%% ==============================================================
% Reset Mouse Position
% ==============================================================

% Recenter the mouse at the fixation cell at the beginning
% of every choice trial.

mouseStartX = round( ...
    mean(ChoiceLayout.fixation([1 3])));

mouseStartY = round( ...
    mean(ChoiceLayout.fixation([2 4])));

SetMouse( ...
    mouseStartX, ...
    mouseStartY, ...
    T.window);

%% ==============================================================
% Response Phase Onset
% ==============================================================

% The clean response display is already present in the onscreen
% backbuffer from drawChoiceSet.
%
% Add the yellow fixation cue before the first response-phase flip.

drawResponseHighlight( ...
    T.window, ...
    ChoiceLayout.fixation, ...
    P.Choice.Highlight.hoverColor, ...
    P.Choice.Highlight.borderWidth);


% This flip marks the true response-phase onset.
choiceOnset = Screen('Flip', T.window);


%% ==============================================================
% Collect Choice Response
% ==============================================================

[response, RT] = collectChoiceResponse( ...
    T.window, ...
    responseBuffer, ...
    ChoiceLayout, ...
    positions.stimulus, ...
    choiceOnset, ...
    P.Choice.choiceDuration, ...
    P.Choice.Highlight);


trial.response = response;
trial.RT = RT;


%% ==============================================================
% Close Response Cache
% ==============================================================

Screen( ...
    'Close', ...
    responseBuffer);


%% ==============================================================
% Missed Trial
% ==============================================================

if isempty(response)

    trial.selectedImage = NaN;

    % Questionnaire fields already contain NaN values.
    % Skip questionnaire after a missed choice.
    return;

end


%% ==============================================================
% Determine Selected Image
% ==============================================================

stimulusIndex = find( ...
    positions.stimulus == response, ...
    1, ...
    'first');


if isempty(stimulusIndex)

    error( ...
        'Choice response location %d does not contain a stimulus.', ...
        response);

end


trial.selectedImage = stimulusIDs(stimulusIndex);


%% ==============================================================
% Questionnaire
% ==============================================================

[questionResponse, questionRT] = runQuestionnaire( ...
    P, ...
    T, ...
    QuestionnaireLayout, ...
    questionFiles);


trial.question.response = questionResponse;
trial.question.RT = questionRT;


end