function [response, RT] = runQuestionnaire( ...
    P, T, Layout, questionFiles)

% runQuestionnaire  Present one questionnaire and collect responses.
%
%   [response, RT] = runQuestionnaire( ...
%       P, T, Layout, questionFiles)
%
%   Presents the questionnaire screen and collects one response for
%   each question.
%
%   Inputs:
%       P             - Parameter structure.
%       T             - Task structure.
%       Layout        - Pixel-based questionnaire layout generated by
%                       convertQuestionnaireLayout.
%       questionFiles - Cell array containing Q0, Q1, Q2, Q3.
%
%   Outputs:
%       response      - 1 x nQuestions vector containing the final
%                       selected Likert responses.
%       RT            - 1 x nQuestions vector containing the time
%                       to the first response for each question.
%
%   The function only controls the sequence of presentation and
%   response collection.


%% ==============================================================
% Initial Display
% ==============================================================

response = nan(1, P.Questionnaire.nQuestions);

drawQuestionnaire( ...
    P, ...
    T, ...
    Layout, ...
    questionFiles, ...
    response);


%% ==============================================================
% Questionnaire Onset
% ==============================================================

startTime = Screen('Flip', T.window);


%% ==============================================================
% Collect Responses
% ==============================================================

[response, RT] = collectQuestionnaireResponse( ...
    T.window, ...
    Layout, ...
    P, ...
    T, ...
    questionFiles, ...
    startTime);

end