
function runRatingPractice(imageIndices, P, T)

%% ==============================================================
% Practice Instructions
% ==============================================================

instructionFolder = ...
    fullfile(P.Experiment.root, 'Instructions');

showInstructionImage( ...
    fullfile(instructionFolder, 'pract_inst_0.png'), ...
    P, ...
    T);
showInstructionImage( ...
    fullfile(instructionFolder, 'pract_inst_1.png'), ...
    P, ...
    T);

%% ==============================================================
% Preference Rating
% ==============================================================

order = imageIndices(randperm(numel(imageIndices)));

practiceRatings = nan(1, P.Images.nImages);

for i = 1:numel(order)

    imageIndex = order(i);

    T.progress = i / numel(order);

    [rating, ~] = runRatingTrial( ...
        P.Images.files{imageIndex}, ...
        P, ...
        T, ...
        "practice");

    practiceRatings(imageIndex) = rating;

end


%% ==============================================================
% Choice Practice Instructions
% ==============================================================

showInstructionImage( ...
    fullfile(instructionFolder, 'pract_inst_2.png'), ...
    P, ...
    T);


%% ==============================================================
% Choice and Questionnaire Practice
% ==============================================================

ChoiceLayout = makeChoiceLayout(P);
ChoiceLayout = convertChoiceLayout( ...
    ChoiceLayout, T.windowRect);

QuestionnaireLayout = makeQuestionnaireLayout(P);
QuestionnaireLayout = convertQuestionnaireLayout( ...
    QuestionnaireLayout, T.windowRect);

questionFiles = P.Questionnaire.questionFiles;

trialCounts = struct( ...
    'UL', 0, ...
    'UM', 0, ...
    'UH', 0, ...
    'CF', 0, ...
    'RS', 1);

for trial = 1:3

    ChoiceSet = makeChoiceSets( ...
        practiceRatings, ...
        6, ...
        P.Choice.RatingRanges, ...
        trialCounts);

    runChoiceTrial( ...
        P, ...
        T, ...
        ChoiceSet(1).imageIDs, ...
        ChoiceSet(1).condition, ...
        ChoiceLayout, ...
        QuestionnaireLayout, ...
        questionFiles);

end

showInstructionImage( ...
    fullfile(instructionFolder, 'pract_inst_3.png'), ...
    P, ...
    T);
end