function R = taskPreferenceRating(R, P, T)

% Instructions
showMessageScreen( ...
    { ...
    'Preference Rating'; ...
    ''; ...
    'You will see picture of mugs.'; ...
    'Rate how much you like each mug.'; ...
    ''; ...
    'LEFT / RIGHT        Move Slider';
    'SPACE            Confirm Rating';
    '';
    'Press SPACE to begin.'}, P, T);


% Round 1
R = runRatingRound(R, P, T, 1);

% Break
showMessageScreen( ...
    { ...
    'Round 1 Completed!'; ...
    ''; ...
    'Take a break.'; ...
    '';
    'Press SPACE to begin round 2.'}, P, T);

% Round 2
R = runRatingRound(R, P, T, 2);

% task-complete
showMessageScreen( ...
    { ...
    'Preference Rating Task Completed!'; ...
    ''; ...
    'good job!'; ...
    ''; ...
    'Call the experimenter.'}, P, T);

% Compute averages
R = computeAverageRating(R);

end