function ratings = getSetRatings(ChoiceSets, rating, setIndex)

% getSetRatings  Return stimulus IDs and ratings for a choice set.
%
%   ratings = getSetRatings(ChoiceSets, rating, setIndex)
%
%   Returns the stimulus IDs and their corresponding ratings for the
%   specified choice set.
%
%   Inputs:
%       ChoiceSets - Struct array generated by makeChoiceSets.
%       rating     - Vector of stimulus ratings indexed by stimulus ID.
%       setIndex   - Index of the choice set to inspect.
%
%   Output:
%       ratings    - Two-column matrix:
%                    column 1: stimulus IDs
%                    column 2: ratings


ids = ChoiceSets(setIndex).imageIDs;

ratings = [ids(:), rating(ids(:))];

end